<?php

/**
 * @file
 * Contains main functions and hooks for svg_image module.
 */

use Drupal\file\Entity\File;
use Drupal\svg_image\Plugin\Field\FieldFormatter\SvgImageFormatter;
use Drupal\svg_image\Plugin\Field\FieldWidget\SvgImageWidget;

/**
 * Implements hook_field_widget_info_alter().
 */
function svg_image_field_widget_info_alter(array &$info) {
  $info['image_image']['class'] = SvgImageWidget::class;
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function svg_image_field_formatter_info_alter(array &$info) {
  $info['image']['class'] = SvgImageFormatter::class;
}

/**
 * Provides image file dimensions.
 *
 * @param \Drupal\file\Entity\File $file
 *   SVG file.
 *
 * @return array
 *   Dimensions array.
 */
function svg_image_get_image_file_dimensions(File $file) {
  /** @var \Drupal\Core\Image\Image $image */
  $image = \Drupal::service('image.factory')->get($file->getFileUri());

  $variables = [];

  if ($image->isValid()) {
    $variables['width'] = $image->getWidth();
    $variables['height'] = $image->getHeight();
  }
  else {
    $variables['width'] = $variables['height'] = NULL;
    // We can find out only dimensions of the SVG files.
    if (svg_image_is_file_svg($file)) {
      // Parse SVG as XML.
      $svg = simplexml_load_string(file_get_contents($file->getFileUri()));
      $neededVariables = ['width', 'height'];

      foreach ($svg->attributes() as $attribute => $value) {
        if (in_array($attribute, $neededVariables)) {
          $variables[$attribute] = (integer) $value;
        }
      }
    }
  }

  return $variables;
}

/**
 * Checks if current file is SVG image.
 *
 * @param \Drupal\file\Entity\File $file
 *   File to check.
 *
 * @return bool
 *   TRUE if is SVG, FALSE otherwise.
 */
function svg_image_is_file_svg(File $file) {
  return $file->getMimeType() === 'image/svg+xml';
}
